
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.0
 * Query Engine version: ab56fe763f921d033a6c195e7ddeb3e255bdbb57
 */
Prisma.prismaVersion = {
  client: "7.4.0",
  engine: "ab56fe763f921d033a6c195e7ddeb3e255bdbb57"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  supabaseUserId: 'supabaseUserId',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  role: 'role',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  firstName: 'firstName',
  lastName: 'lastName',
  phoneNumber: 'phoneNumber',
  birthDate: 'birthDate',
  bio: 'bio',
  profile: 'profile',
  credits: 'credits',
  settings: 'settings',
  twoFactorEnabled: 'twoFactorEnabled',
  twoFactorSecret: 'twoFactorSecret'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  projectName: 'projectName',
  tagline: 'tagline',
  description: 'description',
  data: 'data',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  planId: 'planId',
  status: 'status',
  billingCycle: 'billingCycle',
  startDate: 'startDate',
  endDate: 'endDate',
  autoRenew: 'autoRenew',
  cancelAtPeriodEnd: 'cancelAtPeriodEnd',
  provider: 'provider',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  planId: 'planId',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  gateway: 'gateway',
  trackId: 'trackId',
  refId: 'refId',
  cardPan: 'cardPan',
  description: 'description',
  metadata: 'metadata',
  createdAt: 'createdAt',
  completedAt: 'completedAt',
  refundedAt: 'refundedAt'
};

exports.Prisma.MediaItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  projectId: 'projectId',
  url: 'url',
  category: 'category',
  subcategory: 'subcategory',
  prompt: 'prompt',
  model: 'model',
  createdAt: 'createdAt'
};

exports.Prisma.SystemLogScalarFieldEnum = {
  id: 'id',
  type: 'type',
  action: 'action',
  details: 'details',
  userId: 'userId',
  userEmail: 'userEmail',
  ip: 'ip',
  timestamp: 'timestamp'
};

exports.Prisma.FeedbackScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  message: 'message',
  createdAt: 'createdAt'
};

exports.Prisma.SupportTicketScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  email: 'email',
  subject: 'subject',
  category: 'category',
  priority: 'priority',
  message: 'message',
  status: 'status',
  adminNote: 'adminNote',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SystemSettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.AdminAuditLogScalarFieldEnum = {
  id: 'id',
  actorId: 'actorId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  meta: 'meta',
  createdAt: 'createdAt'
};

exports.Prisma.ProjectMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  projectId: 'projectId',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CanvasScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  name: 'name',
  type: 'type',
  layout: 'layout',
  viewport: 'viewport',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CardScalarFieldEnum = {
  id: 'id',
  canvasId: 'canvasId',
  section: 'section',
  order: 'order',
  x: 'x',
  y: 'y',
  width: 'width',
  height: 'height',
  content: 'content',
  cardType: 'cardType',
  color: 'color',
  metadata: 'metadata',
  createdBy: 'createdBy',
  updatedBy: 'updatedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  canvasId: 'canvasId',
  cardId: 'cardId',
  authorId: 'authorId',
  authorName: 'authorName',
  authorAvatar: 'authorAvatar',
  body: 'body',
  resolved: 'resolved',
  parentId: 'parentId',
  createdAt: 'createdAt'
};

exports.Prisma.CanvasVersionScalarFieldEnum = {
  id: 'id',
  canvasId: 'canvasId',
  name: 'name',
  snapshot: 'snapshot',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.UserProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  role: 'role',
  industry: 'industry',
  businessStage: 'businessStage',
  goals: 'goals',
  preferredTone: 'preferredTone',
  expertiseLevel: 'expertiseLevel',
  language: 'language',
  learnedPreferences: 'learnedPreferences',
  memoryEntries: 'memoryEntries',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TourProgressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  completedTours: 'completedTours',
  skippedTours: 'skippedTours',
  completedChecklistItems: 'completedChecklistItems',
  dismissedBeacons: 'dismissedBeacons',
  persona: 'persona',
  experienceLevel: 'experienceLevel',
  primaryGoal: 'primaryGoal',
  hasSeenWelcome: 'hasSeenWelcome',
  disableAutoStart: 'disableAutoStart',
  lastSeenWhatsNewVersion: 'lastSeenWhatsNewVersion',
  lastKnownProjectType: 'lastKnownProjectType',
  lastKnownPlan: 'lastKnownPlan',
  xp: 'xp',
  level: 'level',
  streak: 'streak',
  lastActiveDate: 'lastActiveDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectMemoryScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  decisions: 'decisions',
  openQuestions: 'openQuestions',
  risks: 'risks',
  keyFacts: 'keyFacts',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChatConversationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  projectId: 'projectId',
  title: 'title',
  mode: 'mode',
  persona: 'persona',
  model: 'model',
  pinned: 'pinned',
  lastMessagePreview: 'lastMessagePreview',
  lastMessageAt: 'lastMessageAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChatMessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  role: 'role',
  content: 'content',
  toolCalls: 'toolCalls',
  artifacts: 'artifacts',
  followUps: 'followUps',
  parentMessageId: 'parentMessageId',
  createdAt: 'createdAt'
};

exports.Prisma.AiFeedbackScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  rating: 'rating',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.ArtifactScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  conversationId: 'conversationId',
  type: 'type',
  refId: 'refId',
  data: 'data',
  version: 'version',
  parentId: 'parentId',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AiActionLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  projectId: 'projectId',
  conversationId: 'conversationId',
  toolName: 'toolName',
  args: 'args',
  result: 'result',
  status: 'status',
  undoPayload: 'undoPayload',
  createdAt: 'createdAt'
};

exports.Prisma.AiInsightScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  projectId: 'projectId',
  type: 'type',
  priority: 'priority',
  title: 'title',
  body: 'body',
  payload: 'payload',
  actionPayload: 'actionPayload',
  status: 'status',
  snoozedUntil: 'snoozedUntil',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AiUsageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  projectId: 'projectId',
  conversationId: 'conversationId',
  model: 'model',
  provider: 'provider',
  feature: 'feature',
  promptTokens: 'promptTokens',
  completionTokens: 'completionTokens',
  totalTokens: 'totalTokens',
  costUsd: 'costUsd',
  success: 'success',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt'
};

exports.Prisma.EmailAiQuotaScalarFieldEnum = {
  emailHash: 'emailHash',
  aiRequests: 'aiRequests',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerBotChannelScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  projectId: 'projectId',
  provider: 'provider',
  credentials: 'credentials',
  config: 'config',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerBotConversationScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  externalId: 'externalId',
  customerName: 'customerName',
  customerHandle: 'customerHandle',
  status: 'status',
  lastMessagePreview: 'lastMessagePreview',
  lastMessageAt: 'lastMessageAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerBotMessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  role: 'role',
  content: 'content',
  externalId: 'externalId',
  metadata: 'metadata',
  isRead: 'isRead',
  createdAt: 'createdAt'
};

exports.Prisma.ScriptScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  title: 'title',
  content: 'content',
  scenes: 'scenes',
  template: 'template',
  duration: 'duration',
  audience: 'audience',
  status: 'status',
  folder: 'folder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  device: 'device',
  platform: 'platform',
  ip: 'ip',
  location: 'location',
  userAgent: 'userAgent',
  lastActive: 'lastActive',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  revokedAt: 'revokedAt'
};

exports.Prisma.LoginEventScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  method: 'method',
  ip: 'ip',
  userAgent: 'userAgent',
  location: 'location',
  createdAt: 'createdAt'
};

exports.Prisma.UserApiKeyScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  label: 'label',
  keyHash: 'keyHash',
  prefix: 'prefix',
  scopes: 'scopes',
  lastUsed: 'lastUsed',
  createdAt: 'createdAt',
  revokedAt: 'revokedAt'
};

exports.Prisma.UserIntegrationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  credentials: 'credentials',
  metadata: 'metadata',
  isConnected: 'isConnected',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DataExportRequestScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  status: 'status',
  format: 'format',
  url: 'url',
  sizeBytes: 'sizeBytes',
  error: 'error',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.KbChunkScalarFieldEnum = {
  id: 'id',
  source: 'source',
  url: 'url',
  section: 'section',
  text: 'text',
  chunkIndex: 'chunkIndex',
  verified: 'verified',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  read: 'read',
  createdAt: 'createdAt',
  action: 'action'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  name: 'name',
  sku: 'sku',
  category: 'category',
  unit: 'unit',
  cost: 'cost',
  price: 'price',
  stock: 'stock',
  lowStockAt: 'lowStockAt',
  supplierId: 'supplierId',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockTransactionScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  productId: 'productId',
  type: 'type',
  qty: 'qty',
  unitCost: 'unitCost',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  name: 'name',
  contact: 'contact',
  address: 'address',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BusinessTransactionScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  type: 'type',
  category: 'category',
  amount: 'amount',
  date: 'date',
  note: 'note',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.StaffScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  name: 'name',
  role: 'role',
  phone: 'phone',
  hourlyRate: 'hourlyRate',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShiftScalarFieldEnum = {
  id: 'id',
  staffId: 'staffId',
  projectId: 'projectId',
  startAt: 'startAt',
  endAt: 'endAt',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.AttendanceEntryScalarFieldEnum = {
  id: 'id',
  staffId: 'staffId',
  projectId: 'projectId',
  checkIn: 'checkIn',
  checkOut: 'checkOut',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.LoyaltyAccountScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  customerId: 'customerId',
  customerName: 'customerName',
  phone: 'phone',
  points: 'points',
  tier: 'tier',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PointTransactionScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  projectId: 'projectId',
  delta: 'delta',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  customerId: 'customerId',
  customerName: 'customerName',
  paymentMethod: 'paymentMethod',
  total: 'total',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  name: 'name',
  qty: 'qty',
  unitPrice: 'unitPrice',
  lineTotal: 'lineTotal'
};

exports.Prisma.PromotionScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  title: 'title',
  type: 'type',
  discountPct: 'discountPct',
  code: 'code',
  startsAt: 'startsAt',
  endsAt: 'endsAt',
  active: 'active',
  copy: 'copy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CouponScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  code: 'code',
  discountPct: 'discountPct',
  discountAmt: 'discountAmt',
  maxUses: 'maxUses',
  usedCount: 'usedCount',
  expiresAt: 'expiresAt',
  active: 'active',
  createdAt: 'createdAt'
};

exports.Prisma.CouponRedemptionScalarFieldEnum = {
  id: 'id',
  couponId: 'couponId',
  projectId: 'projectId',
  customerId: 'customerId',
  createdAt: 'createdAt'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  author: 'author',
  rating: 'rating',
  body: 'body',
  source: 'source',
  reply: 'reply',
  createdAt: 'createdAt'
};

exports.Prisma.ReferralScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  code: 'code',
  referrerId: 'referrerId',
  referrerName: 'referrerName',
  refereeId: 'refereeId',
  status: 'status',
  rewardPoints: 'rewardPoints',
  createdAt: 'createdAt'
};

exports.Prisma.BroadcastScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  channel: 'channel',
  title: 'title',
  body: 'body',
  status: 'status',
  scheduledAt: 'scheduledAt',
  sentAt: 'sentAt',
  recipientCount: 'recipientCount',
  createdAt: 'createdAt'
};

exports.Prisma.AppointmentScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  customerName: 'customerName',
  customerPhone: 'customerPhone',
  service: 'service',
  startAt: 'startAt',
  endAt: 'endAt',
  status: 'status',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  Project: 'Project',
  Subscription: 'Subscription',
  Transaction: 'Transaction',
  MediaItem: 'MediaItem',
  SystemLog: 'SystemLog',
  Feedback: 'Feedback',
  SupportTicket: 'SupportTicket',
  SystemSetting: 'SystemSetting',
  AdminAuditLog: 'AdminAuditLog',
  ProjectMember: 'ProjectMember',
  Canvas: 'Canvas',
  Card: 'Card',
  Comment: 'Comment',
  CanvasVersion: 'CanvasVersion',
  UserProfile: 'UserProfile',
  TourProgress: 'TourProgress',
  ProjectMemory: 'ProjectMemory',
  ChatConversation: 'ChatConversation',
  ChatMessage: 'ChatMessage',
  AiFeedback: 'AiFeedback',
  Artifact: 'Artifact',
  AiActionLog: 'AiActionLog',
  AiInsight: 'AiInsight',
  AiUsage: 'AiUsage',
  EmailAiQuota: 'EmailAiQuota',
  CustomerBotChannel: 'CustomerBotChannel',
  CustomerBotConversation: 'CustomerBotConversation',
  CustomerBotMessage: 'CustomerBotMessage',
  Script: 'Script',
  UserSession: 'UserSession',
  LoginEvent: 'LoginEvent',
  UserApiKey: 'UserApiKey',
  UserIntegration: 'UserIntegration',
  DataExportRequest: 'DataExportRequest',
  KbChunk: 'KbChunk',
  Notification: 'Notification',
  Product: 'Product',
  StockTransaction: 'StockTransaction',
  Supplier: 'Supplier',
  BusinessTransaction: 'BusinessTransaction',
  Staff: 'Staff',
  Shift: 'Shift',
  AttendanceEntry: 'AttendanceEntry',
  LoyaltyAccount: 'LoyaltyAccount',
  PointTransaction: 'PointTransaction',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Promotion: 'Promotion',
  Coupon: 'Coupon',
  CouponRedemption: 'CouponRedemption',
  Review: 'Review',
  Referral: 'Referral',
  Broadcast: 'Broadcast',
  Appointment: 'Appointment'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
