import type { TourDefinition } from "../types";

export const copilotTour: TourDefinition = {
  id: "copilot",
  title: "تور دستیار کارنکس",
  description: "مشاور ۲۴ ساعته اختصاصی",
  accent: "emerald",
  route: "/dashboard/copilot",
  helpCenterHref: "/dashboard/help",
  xpReward: 35,
  checklistItem: true,
  estimatedTime: "۱ دقیقه",
  steps: [
    {
      id: "copilot-welcome",
      target: "copilot-header",
      title: "دستیار هوشمند کارنکس",
      description: "مشاور ۲۴ ساعته اختصاصی شما. این هوش مصنوعی تمام جزئیات پروژه شما را می‌داند.",
      route: "/dashboard/copilot",
      mood: "welcome",
      position: "bottom",
    },
    {
      id: "copilot-templates",
      target: "prompt-templates",
      title: "شروع سریع",
      description: "برای شروع، می‌توانید از این دستورات آماده که مخصوص پروژه شما ساخته شده‌اند استفاده کنید.",
      mood: "tip",
      position: "top",
      offset: 160,
    },
    {
      id: "copilot-input",
      target: "chat-input-container",
      title: "چت با دستیار",
      description: "هر سوالی دارید بپرسید. دستیار کارنکس همیشه آماده پاسخگویی است.",
      mood: "action",
      position: "top",
      offset: 160,
    },
    {
      id: "copilot-mentions",
      target: "chat-input-container",
      title: "منوی اشاره",
      description: "با تایپ @، بخش‌های خاص پروژه را به دستیار بدهید تا دقیقاً روی همان بخش تمرکز کند.",
      type: "pro-tip",
      mood: "tip",
      position: "top",
      offset: 160,
    },
    {
      id: "copilot-upgrade",
      target: "chat-input-container",
      title: "دستیار حرفه‌ای",
      description: "با ارتقا به پلن پرو، به مدل‌های قوی‌تر و پاسخ‌های نامحدود دستیار دسترسی خواهید داشت.",
      type: "pro-tip",
      mood: "tip",
      position: "top",
      offset: 160,
      plans: ["free"],
    },
  ],
};
