import type { TourDefinition } from "../types";

export const dashboardTour: TourDefinition = {
  id: "dashboard",
  title: "تور پیشخوان",
  description: "آشنایی با داشبورد و ابزارهای اصلی",
  accent: "primary",
  route: "/dashboard/overview",
  helpCenterHref: "/dashboard/help",
  xpReward: 50,
  checklistItem: true,
  estimatedTime: "۱ دقیقه",
  steps: [
    {
      id: "welcome",
      target: "dashboard-root",
      title: "به کارنکس خوش آمدید",
      description: "در اینجا نمایی کلی از وضعیت پروژه، ابزارها و آمارهای کلیدی خود را مشاهده می‌کنید.",
      type: "centered",
      mood: "welcome",
      position: "bottom",
    },
    {
      id: "sidebar",
      target: "sidebar-nav",
      title: "جعبه ابزار شما",
      description: "دسترسی سریع به تمام بخش‌های پروژه: از بوم مدل کسب‌وکار تا نقشه راه و پیچ‌دک.",
      mood: "tip",
      position: "left",
    },
    {
      id: "stats",
      target: "overview-focus",
      title: "گام بعدی شما",
      description: "مهم‌ترین کار فعلی پروژه‌تان اینجا دیده می‌شود؛ از همین‌جا وارد نقشه راه یا دستیار شوید.",
      mood: "tip",
      position: "bottom",
    },
    {
      id: "help",
      target: "help-button",
      title: "مرکز راهنما",
      description: "هر زمان نیاز به راهنمایی داشتید، از اینجا تورها را بازپخش کنید یا چک‌لیست را ببینید.",
      mood: "action",
      position: "bottom",
    },
    {
      id: "admin-panel",
      target: "sidebar-nav",
      title: "پنل مدیریت",
      description: "به‌عنوان مدیر، به بخش مدیریت کاربران و گزارش‌های سیستم دسترسی دارید.",
      mood: "tip",
      position: "left",
      type: "pro-tip",
      roles: ["admin"],
    },
    {
      id: "finish",
      target: "dashboard-root",
      title: "شروع کنید!",
      description: "تور آموزشی به پایان رسید. حالا می‌توانید با استفاده از بخش‌های مختلف، مدیریت پروژه خود را آغاز کنید.",
      type: "centered",
      mood: "success",
      position: "bottom",
    },
  ],
};
