import type { TourDefinition } from "../types";

export const locationAnalyzerTour: TourDefinition = {
  id: "location-analyzer",
  title: "تور تحلیل موقعیت",
  description: "تحلیل حرفه‌ای موقعیت مکانی",
  accent: "teal",
  route: "/dashboard/location",
  helpCenterHref: "/dashboard/help",
  xpReward: 40,
  checklistItem: true,
  estimatedTime: "۱ دقیقه",
  projectTypes: ["traditional"],
  steps: [
    {
      id: "location-welcome",
      target: "location-header",
      title: "هاب هوشمند موقعیت",
      description: "تحلیل‌های عمیق و حرفه‌ای از هر موقعیت مکانی.",
      route: "/dashboard/location",
      mood: "welcome",
      position: "bottom",
    },
    {
      id: "location-search",
      target: "location-search",
      title: "جستجوی دقیق",
      description: "شهر و آدرس دقیق ملک را وارد کنید تا آنالیز شروع شود.",
      mood: "action",
      position: "bottom",
    },
    {
      id: "location-tabs",
      target: "location-tabs",
      title: "ابعاد مختلف تحلیل",
      description: "نتایج در بخش‌های رقبا، جمعیت‌شناسی، SWOT و پیشنهادات عملیاتی دسته‌بندی شده‌اند.",
      mood: "tip",
      position: "top",
    },
    {
      id: "location-history",
      target: "history-btn",
      title: "تاریخچه تحلیل‌ها",
      description: "تمام تحلیل‌های قبلی شما اینجا ذخیره می‌شوند.",
      mood: "tip",
      position: "bottom",
    },
    {
      id: "location-compare",
      target: "compare-btn",
      title: "مقایسه پیشرفته",
      description: "می‌توانید تا ۳ موقعیت مختلف را برای مقایسه دقیق کنار هم قرار دهید.",
      mood: "success",
      position: "bottom",
    },
  ],
};
